Name : **A.SAIRAM**

Roll : **21X05A6701**

Stream : **DataScience**

College : **Narsimha Reddy Engineering College**

**Project Title** : To Predict the Heartattack disease for organization (WHO:World Health Organization) using machine learning algorithm rate of heart attack disease will increasing manner or decreasing manner

**Problem Statement**: A WHO estimated 12 millions death records. One of them half off the death result is found in US. There search scholars point out the relevant risk factor of heart attack as a DataScience engineer predict the overall risk using ML algorithm(Logistic Regression)


**Task** :
1) Import the libraries required for prediction.

2) Import the Dataset using workspace.

3) Use the appropriate argument of sklearn Library to train,test and split the dataset

4) Fit your values with a range function using feature scalling

5) Check your model accuracy and precison using confusion matrix



**Conclusion** : According to the model analysis the Logistic Regression Algorithm works successfully with 0.6 accuracy.

The accuracy shows that building model is successfull



In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("framingham.csv")
data

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

In [15]:
from sklearn.model_selection import train_test_split
X=data[["age"]]
y=data["currentSmoker"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [16]:
print(X_train)


      age
3252   40
3946   57
1261   47
2536   41
4089   64
...   ...
3444   36
466    57
3092   60
3772   39
860    35

[3390 rows x 1 columns]


In [17]:
print(y_train)

3252    1
3946    0
1261    0
2536    1
4089    0
       ..
3444    1
466     1
3092    0
3772    1
860     0
Name: currentSmoker, Length: 3390, dtype: int64


In [18]:
print(X_test)

      age
3188   63
764    45
3264   51
1967   45
2185   45
...   ...
3303   47
4056   44
4210   50
3971   64
2540   55

[848 rows x 1 columns]


In [19]:
print(y_test)

3188    0
764     0
3264    1
1967    1
2185    1
       ..
3303    0
4056    0
4210    0
3971    0
2540    1
Name: currentSmoker, Length: 848, dtype: int64


In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
print(X_train)

[[-1.11033368]
 [ 0.87196279]
 [-0.29409396]
 ...
 [ 1.22177981]
 [-1.22693936]
 [-1.69336206]]


In [22]:
print(X_test)

[[ 1.57159684]
 [-0.52730531]
 [ 0.17232874]
 [-0.52730531]
 [-0.52730531]
 [ 0.17232874]
 [ 0.05572307]
 [ 1.22177981]
 [ 1.33838549]
 [ 0.75535712]
 [ 0.40554009]
 [ 0.63875144]
 [-1.57675638]
 [-0.06088261]
 [ 1.80480819]
 [-0.87712233]
 [ 1.33838549]
 [-0.52730531]
 [ 0.52214577]
 [ 1.68820251]
 [ 1.10517414]
 [-1.34354503]
 [-0.06088261]
 [-1.46015071]
 [ 0.87196279]
 [ 1.10517414]
 [-1.34354503]
 [-0.52730531]
 [ 0.28893442]
 [-0.17748828]
 [ 0.52214577]
 [-1.22693936]
 [ 0.52214577]
 [ 0.17232874]
 [-0.99372801]
 [-1.22693936]
 [-0.64391098]
 [-0.99372801]
 [ 0.63875144]
 [ 0.05572307]
 [ 0.28893442]
 [ 0.63875144]
 [ 1.33838549]
 [-0.29409396]
 [-0.76051666]
 [-0.87712233]
 [ 0.87196279]
 [-1.22693936]
 [-0.87712233]
 [ 2.27123089]
 [-0.99372801]
 [ 0.40554009]
 [ 1.33838549]
 [-0.06088261]
 [-0.99372801]
 [-0.29409396]
 [ 1.57159684]
 [ 1.33838549]
 [-0.99372801]
 [-0.99372801]
 [ 0.40554009]
 [ 0.98856846]
 [-0.64391098]
 [-0.52730531]
 [ 0.52214577]
 [-0.99372801]
 [ 0.87196

In [23]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [25]:
y_pred = classifier.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[263 183]
 [155 247]]


0.6014150943396226